[package]
name = "wildcard-querier"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.0.0"
anyhow = "1.0.93"
nanoid = "0.4.0"
repeater = { path = "./repeater" }
rand = "0.8.5"


[dev-dependencies]
divan = "0.1.15"

[[bench]]
name = "bench"
harness = false
